export const SINGLE_SELECT = 'SINGLE_SELECT';
export const MULTI_SELECT = 'MULTI_SELECT';
export const IMAGE_SINGLE_SELECT = 'IMAGE_SINGLE_SELECT';
export const IMAGE_MULTI_SELECT = 'IMAGE_MULTI_SELECT';
export const TEXT_FIELD = 'TEXT_FIELD';
